const { contextBridge, ipcRenderer } = require("electron");

// 渲染层只能通过这个白名单接口访问主进程，不暴露 node。
contextBridge.exposeInMainWorld("voah", {
  listProducts: () => ipcRenderer.invoke("voah:listProducts"),
  listTaskCenter: () => ipcRenderer.invoke("voah:listTaskCenter"),
  acknowledgeTask: (task) => ipcRenderer.invoke("voah:acknowledgeTask", task),
  continueIntakeTask: (task) => ipcRenderer.invoke("voah:continueIntakeTask", task),
  inspectProduct: (slug) => ipcRenderer.invoke("voah:inspectProduct", slug),
  createProduct: (params) => ipcRenderer.invoke("voah:createProduct", params),
  saveProductDetail: (params) => ipcRenderer.invoke("voah:saveProductDetail", params),
  listIntakeRuns: (slug) => ipcRenderer.invoke("voah:listIntakeRuns", slug),
  startIntake: (params) => ipcRenderer.invoke("voah:startIntake", params),
  chooseDirectory: () => ipcRenderer.invoke("voah:chooseDirectory"),
  listBatches: () => ipcRenderer.invoke("voah:listBatches"),
  taskDetail: (taskDir) => ipcRenderer.invoke("voah:taskDetail", taskDir),
  createBatch: (params) => ipcRenderer.invoke("voah:createBatch", params),
  retryTask: (params) => ipcRenderer.invoke("voah:retryTask", params),
  continueTask: (params) => ipcRenderer.invoke("voah:continueTask", params),
  pauseBatch: (batchDir) => ipcRenderer.invoke("voah:pauseBatch", batchDir),
  resumeBatch: (batchDir) => ipcRenderer.invoke("voah:resumeBatch", batchDir),
  readTaskLog: (params) => ipcRenderer.invoke("voah:readTaskLog", params),
  listOutputs: () => ipcRenderer.invoke("voah:listOutputs"),
  saveReview: (params) => ipcRenderer.invoke("voah:saveReview", params),
  getConfig: () => ipcRenderer.invoke("voah:getConfig"),
  setConfig: (params) => ipcRenderer.invoke("voah:setConfig", params),
  getStudioSettings: () => ipcRenderer.invoke("voah:getStudioSettings"),
  saveStudioSettings: (params) => ipcRenderer.invoke("voah:saveStudioSettings", params),
  listTtsVoices: () => ipcRenderer.invoke("voah:listTtsVoices"),
  listSubtitleFonts: () => ipcRenderer.invoke("voah:listSubtitleFonts"),
  installSubtitleFont: (fontId) => ipcRenderer.invoke("voah:installSubtitleFont", fontId),
  createSampleTask: (params) => ipcRenderer.invoke("voah:createSampleTask", params),
  runCopyStage: (taskDir) => ipcRenderer.invoke("voah:runCopyStage", taskDir),
  runTtsStage: (taskDir) => ipcRenderer.invoke("voah:runTtsStage", taskDir),
  ttsPreview: (params) => ipcRenderer.invoke("voah:ttsPreview", params),
  saveVoiceScript: (params) => ipcRenderer.invoke("voah:saveVoiceScript", params),
  reveal: (target) => ipcRenderer.invoke("voah:reveal", target),
  openFile: (target) => ipcRenderer.invoke("voah:openFile", target)
});
